# URL = "jdbc:mysql://localhost:3307/data_engineering" 
# DRIVER = "com.mysql.cj.jdbc.Driver"
# USER = "root"
# PASSWORD = "1"
USER = 'root'
PASSWORD = '1'
HOST = 'localhost'
PORT = '3307'
DB_NAME = 'data_engineering'
URL = 'jdbc:mysql://' + HOST + ':' + PORT + '/' + DB_NAME
DRIVER = "com.mysql.cj.jdbc.Driver"